#Base de dados
CET(matematica)
CET(probabilidade_e_estatistica)
CET(ciencia_da_computacao)
CET(fisica)
subarea(programacao, ciencia_da_computacao)
subarea(computacao_e_algoritmos, ciencia_da_computacao)
subarea(arquitetura_de_computadores, ciencia_da_computacao)
subarea(matematica, ciencia_da_computacao)
subarea(fisica_e_eletricidade, ciencia_da_computacao)
subarea(pedagogia, ciencia_da_computacao)
subarea(mecanica, fisica)
subarea(termodinamica, ciencia_da_computacao)
subarea(eletromagnetismo, fisica)
subarea(fisica_ondulatoria, fisica)
subarea(calculo_diferencial_e_integral, fisica)
subarea(geometria_analitica, fisica)
disciplina_subarea(d1, programacao)
disciplina_subarea(d2, programacao)
disciplina_subarea(d3, computacao_e_algoritmos)
disciplina_subarea(d4, computacao_e_algoritmos)
disciplina_subarea(d5, matematica)
disciplina_subarea(d6, fisica_e_eletricidade)
disciplina_subarea(d7, pedagogia)
disciplina_subarea(d8, mecanica)
disciplina_subarea(d9, mecanica)
disciplina_subarea(d10, termodinamica)
disciplina_subarea(d11, eletromagnetismo)
disciplina_subarea(d12, fisica_ondulatoria)
disciplina_subarea(d13, calculo_diferencial_e_integral)
disciplina_subarea(d14, geometria_analitica)
disciplina_curso(d1, bacharelado, ciencia_da_computacao)
disciplina_curso(d2, bacharelado, ciencia_da_computacao)
disciplina_curso(d3, bacharelado, ciencia_da_computacao)
disciplina_curso(d4, bacharelado, ciencia_da_computacao)
disciplina_curso(d5, bacharelado, ciencia_da_computacao)
disciplina_curso(d6, bacharelado, ciencia_da_computacao)
disciplina_curso(d8, bacharelado, fisica)
disciplina_curso(d9, bacharelado, fisica)
disciplina_curso(d10, bacharelado, fisica)
disciplina_curso(d11, bacharelado, fisica)
disciplina_curso(d12, licenciatura, fisica)
disciplina_curso(d13, licenciatura, fisica)
disciplina_curso(d14, licenciatura, fisica)
ccet(ciencia_da_computacao, bacharelado)
ccet(fisica, bacharelado)
ccet(fisica, licenciatura)
lotado_em(p1, ciencia_da_computacao, bacharelado)
lotado_em(p2, ciencia_da_computacao, bacharelado)
lotado_em(p3, ciencia_da_computacao, bacharelado)
lotado_em(p4, fisica, bacharelado)
lotado_em(p5, fisica, bacharelado)
lotado_em(p6, fisica, bacharelado)
lotado_em(p7, fisica, licenciatura)
lotado_em(p8, fisica, licenciatura)
lotado_em(p9, fisica, licenciatura)
ministrada(p1, d1)
ministrada(p1, d2)
ministrada(p1, d3)
ministrada(p1, d11)
ministrada(p2 , d4)
ministrada(p2 , d5)
ministrada(p3 , d6)
ministrada(p3 , d7)
ministrada(p4 , d8)
ministrada(p4 , d13)
ministrada(p5 , d9)
ministrada(p6 , d10)
ministrada(p6 , d11)
ministrada(p8 , d12)
ministrada(p8 , d13)
ministrada(p9 , d8)
ministrada(p9 , d14)

#Regras
ministrada_por(X, Y):- ministra(X, Y)
